### ISSUE TITLE
Fehler in index.php für php8

### ISSUE THREAD

**Issue by Cubikon** [homematic-community/homehub#3]
Lässt sich in php 8.3 nicht starten. 
Error in Zeile 180: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given
`if(count($export) > 0) `
muss zu 
`if(count((array)$export) > 0)`

EDIT: bzw. es tauchen mehrere der fehler auf, die müssten alle angepasst werden

**Comment by christian1180** [comment]
Mit PHP Version 8.3.6 unter IIS nicht nachstellbar. Danke für den Hinweis wurde korrigiert.
